### ISSUE TITLE
ghost Snakemake all rules

### ISSUE THREAD

**Issue by charlesreid1** [dahak-metagenomics/dahak-taco#17]
a la spacegraphcats (link?):

add a rule that takes what the user wants to provide (input files) and maps to what snakemake wants the user to provide (output files). 

this keeps everyone happy: the user provides input files like a normal sane human being, and snakemake gets output files, which it can use to build the task graph.

**Comment by ctb** [comment]
On Fri, May 11, 2018 at 04:25:17AM -0700, Chaz Reid wrote:
> a la spacegraphcats (link?):

https://github.com/spacegraphcats/spacegraphcats/blob/master/conf/Snakefile#L59

**Comment by charlesreid1** [comment]
[This](https://github.com/spacegraphcats/spacegraphcats/blob/master/conf/run#L72-L77) is a nice interface to provide: various named Snakemake targets.

* build 
* searchquick
* search
* clean

User can specify a named target in their workflow config file. Their list of input files is moved to the parameters, and the user is no longer specifying filenames for targets.

The ghost target rule would take an input file pattern or a list of input files from the parameters file, and assemble that into file names that it specifies as inputs to the rule (no outputs).
