### ISSUE TITLE
Why separate config and parameter files?

### ISSUE THREAD

**Issue by charlesreid1** [dahak-metagenomics/dahak-taco#19]
Occam's Razor: we should clarify the reasoning for separating the workflow config and workflow parameter files (otherwise, simplify and combine them).

I think our final consensus will be to keep them separate, but should clarify this in documentation.

### Split the files

Pro: makes it easier to define and switch out parameter sets for a given workflow

Con: possibly confusing, more things to keep track of and specify on command line

### Combine the files

Pro: simpler

Con: less flexible

**Comment by ctb** [comment]
On Mon, May 14, 2018 at 02:53:26PM -0700, Chaz Reid wrote:
> ### Split the files
> 
> Pro: makes it easier to define and switch out parameter sets for a given workflow
> 
> Con: possibly confusing, more things to keep track of and specify on command line

It was an explicit goal of mine to do this, because we want to be able to
provide e.g. "hard" and "soft" trimming parameters.  But sensible defaults are
good to have.
