### ISSUE TITLE
Links are broken in walkthrough github page

### ISSUE THREAD

**Issue by SichongP** [dahak-metagenomics/dahak-taco#2]
In this page (https://dahak-metagenomics.github.io/dahak-taco/walkthrus/readfilt.html)
hyperlinks pointing to 
https://dahak-metagenomics.github.io/INSTALLING.md
and
https://dahak-metagenomics.github.io/dahak-taco/walkthrus/setup.md
are broken and lead to 404

**Comment by charlesreid1** [comment]
NLA
