### ISSUE TITLE
use_local not defined

### ISSUE THREAD

**Issue by SichongP** [dahak-metagenomics/dahak-taco#3]
When I follow walkthrough to run firs step of read filtering, variable ```use_local``` is not defined and causes program to break in ```pre_post_assessment.rule```
It is not clear from the documentation as to whether, where, and when a user needs to set ```use_local```. It's not seen in ```config``` hash either.

**Comment by charlesreid1** [comment]
Hmm... I had to use this setting to shim a local docker image in place of the (broken) biocontainers image. Today I realized this had broken a few other things. Am currently working on fixing this...

**Comment by charlesreid1** [comment]
NLA with latest changes, closing...
