### ISSUE TITLE
top-level webpage for dahak-metagenomics?

### ISSUE THREAD

**Issue by ljcohen** [dahak-metagenomics/dahak-taco#5]
This page does not contain anything:

https://dahak-metagenomics.github.io/

Someone who is curious might be interested to learn what the top-level organization is?

**Comment by charlesreid1** [comment]
Thanks for opening this issue! We've got some content in the dahak-metagenomics/dahak repo so I think we can turn that into an HTML page.

Also see dahak-metagenomics/dahak#76

**Comment by charlesreid1** [comment]
done - see [dahak-metagenomics.github.io/](https://dahak-metagenomics.github.io/) and corresponding [repo](https://github.com/dahak-metagenomics/dahak-metagenomics.github.io).
